spring:
  application:
    name: nnpia
server:
  port: 8081

  server:
    port: 8081
    servlet:
      context-path: /api
  spring:
    application:
      name: "nnpia"
    datasource:
      url: "jdbc:postgresql://localhost:5432/nnpia"
      username: "to-be-replace"
      password: "to-be-replace"
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          show_sql: true;
          format_sql: true
  springdoc:
    swagger-ui:
      path: /swagger
    api-docs:
      path: /swagger-docs
  jwt:
    secret: "to-be-replace"
  logging:
    level:
      org:
        hibernate:
          type: trace
